In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns                                      #sklearn has the all the ML files prewritten so we just import them
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import BaggingRegressor

In [3]:
data=pd.read_csv('kc_house_data.csv')

In [4]:
data

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,...,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
10,1736800520,20150403T000000,662500.0,3,2.50,3560,9796,1.0,0,0,...,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
11,9212900260,20140527T000000,468000.0,2,1.00,1160,6000,1.0,0,0,...,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
12,114101516,20140528T000000,310000.0,3,1.00,1430,19901,1.5,0,0,...,7,1430,0,1927,0,98028,47.7558,-122.229,1780,12697
13,6054650070,20141007T000000,400000.0,3,1.75,1370,9680,1.0,0,0,...,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208
14,1175000570,20150312T000000,530000.0,5,2.00,1810,4850,1.5,0,0,...,7,1810,0,1900,0,98107,47.6700,-122.394,1360,4850
15,9297300055,20150124T000000,650000.0,4,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
16,1875500060,20140731T000000,395000.0,3,2.00,1890,14040,2.0,0,0,...,7,1890,0,1994,0,98019,47.7277,-121.962,1890,14018
17,6865200140,20140529T000000,485000.0,4,1.00,1600,4300,1.5,0,0,...,7,1600,0,1916,0,98103,47.6648,-122.343,1610,4300
18,16000397,20141205T000000,189000.0,2,1.00,1200,9850,1.0,0,0,...,7,1200,0,1921,0,98002,47.3089,-122.210,1060,5095
19,7983200060,20150424T000000,230000.0,3,1.00,1250,9774,1.0,0,0,...,7,1250,0,1969,0,98003,47.3343,-122.306,1280,8850
20,6300500875,20140514T000000,385000.0,4,1.75,1620,4980,1.0,0,0,...,7,860,760,1947,0,98133,47.7025,-122.341,1400,4980
21,2524049179,20140826T000000,2000000.0,3,2.75,3050,44867,1.0,0,4,...,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
22,7137970340,20140703T000000,285000.0,5,2.50,2270,6300,2.0,0,0,...,8,2270,0,1995,0,98092,47.3266,-122.169,2240,7005
23,8091400200,20140516T000000,252700.0,2,1.50,1070,9643,1.0,0,0,...,7,1070,0,1985,0,98030,47.3533,-122.166,1220,8386
24,3814700200,20141120T000000,329000.0,3,2.25,2450,6500,2.0,0,0,...,8,2450,0,1985,0,98030,47.3739,-122.172,2200,6865
25,1202000200,20141103T000000,233000.0,3,2.00,1710,4697,1.5,0,0,...,6,1710,0,1941,0,98002,47.3048,-122.218,1030,4705
26,1794500383,20140626T000000,937000.0,3,1.75,2450,2691,2.0,0,0,...,8,1750,700,1915,0,98119,47.6386,-122.360,1760,3573
27,3303700376,20141201T000000,667000.0,3,1.00,1400,1581,1.5,0,0,...,8,1400,0,1909,0,98112,47.6221,-122.314,1860,3861
28,5101402488,20140624T000000,438000.0,3,1.75,1520,6380,1.0,0,0,...,7,790,730,1948,0,98115,47.6950,-122.304,1520,6235
29,1873100390,20150302T000000,719000.0,4,2.50,2570,7173,2.0,0,0,...,8,2570,0,2005,0,98052,47.7073,-122.110,2630,6026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21583,2025049203,20140610T000000,399950.0,2,1.00,710,1157,2.0,0,0,...,7,710,0,1943,0,98102,47.6413,-122.329,1370,1173
21584,952006823,20141202T000000,380000.0,3,2.50,1260,900,2.0,0,0,...,7,940,320,2007,0,98116,47.5621,-122.384,1310,1415
21585,3832050760,20140828T000000,270000.0,3,2.50,1870,5000,2.0,0,0,...,7,1870,0,2009,0,98042,47.3339,-122.055,2170,5399
21586,2767604724,20141015T000000,505000.0,2,2.50,1430,1201,3.0,0,0,...,8,1430,0,2009,0,98107,47.6707,-122.381,1430,1249
21587,6632300207,20150305T000000,385000.0,3,2.50,1520,1488,3.0,0,0,...,8,1520,0,2006,0,98125,47.7337,-122.309,1520,1497
21588,2767600688,20141113T000000,414500.0,2,1.50,1210,1278,2.0,0,0,...,8,1020,190,2007,0,98117,47.6756,-122.375,1210,1118
21589,7570050450,20140910T000000,347500.0,3,2.50,2540,4760,2.0,0,0,...,8,2540,0,2010,0,98038,47.3452,-122.022,2540,4571
21590,7430200100,20140514T000000,1222500.0,4,3.50,4910,9444,1.5,0,0,...,11,3110,1800,2007,0,98074,47.6502,-122.066,4560,11063
21591,4140940150,20141002T000000,572000.0,4,2.75,2770,3852,2.0,0,0,...,8,2770,0,2014,0,98178,47.5001,-122.232,1810,5641
21592,1931300412,20150416T000000,475000.0,3,2.25,1190,1200,3.0,0,0,...,8,1190,0,2008,0,98103,47.6542,-122.346,1180,1224
21593,8672200110,20150317T000000,1088000.0,5,3.75,4170,8142,2.0,0,2,...,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21594,5087900040,20141017T000000,350000.0,4,2.75,2500,5995,2.0,0,0,...,8,2500,0,2008,0,98042,47.3749,-122.107,2530,5988
21595,1972201967,20141031T000000,520000.0,2,2.25,1530,981,3.0,0,0,...,8,1480,50,2006,0,98103,47.6533,-122.346,1530,1282
21596,7502800100,20140813T000000,679950.0,5,2.75,3600,9437,2.0,0,0,...,9,3600,0,2014,0,98059,47.4822,-122.131,3550,9421
21597,191100405,20150421T000000,1575000.0,4,3.25,3410,10125,2.0,0,0,...,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125
21598,8956200760,20141013T000000,541800.0,4,2.50,3118,7866,2.0,0,2,...,9,3118,0,2014,0,98001,47.2931,-122.264,2673,6500
21599,7202300110,20140915T000000,810000.0,4,3.00,3990,7838,2.0,0,0,...,9,3990,0,2003,0,98053,47.6857,-122.046,3370,6814
21600,249000205,20141015T000000,1537000.0,5,3.75,4470,8088,2.0,0,0,...,11,4470,0,2008,0,98004,47.6321,-122.200,2780,8964
21601,5100403806,20150407T000000,467000.0,3,2.50,1425,1179,3.0,0,0,...,8,1425,0,2008,0,98125,47.6963,-122.318,1285,1253
21602,844000965,20140626T000000,224000.0,3,1.75,1500,11968,1.0,0,0,...,6,1500,0,2014,0,98010,47.3095,-122.002,1320,11303
21603,7852140040,20140825T000000,507250.0,3,2.50,2270,5536,2.0,0,0,...,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,9834201367,20150126T000000,429000.0,3,2.00,1490,1126,3.0,0,0,...,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21605,3448900210,20141014T000000,610685.0,4,2.50,2520,6023,2.0,0,0,...,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,7936000429,20150326T000000,1007500.0,4,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21607,2997800021,20150219T000000,475000.0,3,2.50,1310,1294,2.0,0,0,...,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [5]:
data['date']=pd.to_datetime(data['date'])
print(data['date'])

0       2014-10-13
1       2014-12-09
2       2015-02-25
3       2014-12-09
4       2015-02-18
5       2014-05-12
6       2014-06-27
7       2015-01-15
8       2015-04-15
9       2015-03-12
10      2015-04-03
11      2014-05-27
12      2014-05-28
13      2014-10-07
14      2015-03-12
15      2015-01-24
16      2014-07-31
17      2014-05-29
18      2014-12-05
19      2015-04-24
20      2014-05-14
21      2014-08-26
22      2014-07-03
23      2014-05-16
24      2014-11-20
25      2014-11-03
26      2014-06-26
27      2014-12-01
28      2014-06-24
29      2015-03-02
           ...
21583   2014-06-10
21584   2014-12-02
21585   2014-08-28
21586   2014-10-15
21587   2015-03-05
21588   2014-11-13
21589   2014-09-10
21590   2014-05-14
21591   2014-10-02
21592   2015-04-16
21593   2015-03-17
21594   2014-10-17
21595   2014-10-31
21596   2014-08-13
21597   2015-04-21
21598   2014-10-13
21599   2014-09-15
21600   2014-10-15
21601   2015-04-07
21602   2014-06-26
21603   2014-08-25
21604   2015-01-26
21605   2014-10-14
21606   2015-03-26
21607   2015-02-19
21608   2014-05-21
21609   2015-02-23
21610   2014-06-23
21611   2015-01-16
21612   2014-10-15
Name: date, Length: 21613, dtype: datetime64[ns]

In [6]:
data['month']=data['date'].dt.month
print(data['month'])

0        10
1        12
2         2
3        12
4         2
5         5
6         6
7         1
8         4
9         3
10        4
11        5
12        5
13       10
14        3
15        1
16        7
17        5
18       12
19        4
20        5
21        8
22        7
23        5
24       11
25       11
26        6
27       12
28        6
29        3
         ..
21583     6
21584    12
21585     8
21586    10
21587     3
21588    11
21589     9
21590     5
21591    10
21592     4
21593     3
21594    10
21595    10
21596     8
21597     4
21598    10
21599     9
21600    10
21601     4
21602     6
21603     8
21604     1
21605    10
21606     3
21607     2
21608     5
21609     2
21610     6
21611     1
21612    10
Name: month, Length: 21613, dtype: int64

In [7]:
data['year']=data['date'].dt.year
print(data['year'])

0        2014
1        2014
2        2015
3        2014
4        2015
5        2014
6        2014
7        2015
8        2015
9        2015
10       2015
11       2014
12       2014
13       2014
14       2015
15       2015
16       2014
17       2014
18       2014
19       2015
20       2014
21       2014
22       2014
23       2014
24       2014
25       2014
26       2014
27       2014
28       2014
29       2015
         ...
21583    2014
21584    2014
21585    2014
21586    2014
21587    2015
21588    2014
21589    2014
21590    2014
21591    2014
21592    2015
21593    2015
21594    2014
21595    2014
21596    2014
21597    2015
21598    2014
21599    2014
21600    2014
21601    2015
21602    2014
21603    2014
21604    2015
21605    2014
21606    2015
21607    2015
21608    2014
21609    2015
21610    2014
21611    2015
21612    2014
Name: year, Length: 21613, dtype: int64

In [8]:
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,month,year
0,7129300520,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0,0,...,0,1955,0,98178,47.5112,-122.257,1340,5650,10,2014
1,6414100192,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0,0,...,400,1951,1991,98125,47.7210,-122.319,1690,7639,12,2014
2,5631500400,2015-02-25,180000.0,2,1.00,770,10000,1.0,0,0,...,0,1933,0,98028,47.7379,-122.233,2720,8062,2,2015
3,2487200875,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0,0,...,910,1965,0,98136,47.5208,-122.393,1360,5000,12,2014
4,1954400510,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0,0,...,0,1987,0,98074,47.6168,-122.045,1800,7503,2,2015

In [9]:
data.shape

(21613, 23)

In [10]:
data.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,month,year
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,...,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,...,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652,6.574423,2014.322954
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,...,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631,3.115308,0.467616
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,...,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,1.000000,2014.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,...,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000,4.000000,2014.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,...,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000,6.000000,2014.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,...,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000,9.000000,2015.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,...,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,12.000000,2015.000000

In [11]:
curryear=pd.datetime.now().year      #current year - system generated
print(curryear)

2019

In [12]:
house_age=curryear-data['yr_built']
print(house_age)

0         64
1         68
2         86
3         54
4         32
5         18
6         24
7         56
8         59
9         16
10        54
11        77
12        92
13        42
14       119
15        40
16        25
17       103
18        98
19        50
20        72
21        51
22        24
23        34
24        34
25        78
26       104
27       110
28        71
29        14
        ...
21583     76
21584     12
21585     10
21586     10
21587     13
21588     12
21589      9
21590     12
21591      5
21592     11
21593     13
21594     11
21595     13
21596      5
21597     12
21598      5
21599     16
21600     11
21601     11
21602      5
21603     16
21604      5
21605      5
21606     10
21607     11
21608     10
21609      5
21610     10
21611     15
21612     11
Name: yr_built, Length: 21613, dtype: int64

In [13]:
data=data.rename(columns={'yr_built':'houseagenow'})     #renaming column
print(data)

               id       date      price  bedrooms  bathrooms  sqft_living  \
0      7129300520 2014-10-13   221900.0         3       1.00         1180
1      6414100192 2014-12-09   538000.0         3       2.25         2570
2      5631500400 2015-02-25   180000.0         2       1.00          770
3      2487200875 2014-12-09   604000.0         4       3.00         1960
4      1954400510 2015-02-18   510000.0         3       2.00         1680
5      7237550310 2014-05-12  1225000.0         4       4.50         5420
6      1321400060 2014-06-27   257500.0         3       2.25         1715
7      2008000270 2015-01-15   291850.0         3       1.50         1060
8      2414600126 2015-04-15   229500.0         3       1.00         1780
9      3793500160 2015-03-12   323000.0         3       2.50         1890
10     1736800520 2015-04-03   662500.0         3       2.50         3560
11     9212900260 2014-05-27   468000.0         2       1.00         1160
12      114101516 2014-05-28   310000.0         3       1.00         1430
13     6054650070 2014-10-07   400000.0         3       1.75         1370
14     1175000570 2015-03-12   530000.0         5       2.00         1810
15     9297300055 2015-01-24   650000.0         4       3.00         2950
16     1875500060 2014-07-31   395000.0         3       2.00         1890
17     6865200140 2014-05-29   485000.0         4       1.00         1600
18       16000397 2014-12-05   189000.0         2       1.00         1200
19     7983200060 2015-04-24   230000.0         3       1.00         1250
20     6300500875 2014-05-14   385000.0         4       1.75         1620
21     2524049179 2014-08-26  2000000.0         3       2.75         3050
22     7137970340 2014-07-03   285000.0         5       2.50         2270
23     8091400200 2014-05-16   252700.0         2       1.50         1070
24     3814700200 2014-11-20   329000.0         3       2.25         2450
25     1202000200 2014-11-03   233000.0         3       2.00         1710
26     1794500383 2014-06-26   937000.0         3       1.75         2450
27     3303700376 2014-12-01   667000.0         3       1.00         1400
28     5101402488 2014-06-24   438000.0         3       1.75         1520
29     1873100390 2015-03-02   719000.0         4       2.50         2570
...           ...        ...        ...       ...        ...          ...
21583  2025049203 2014-06-10   399950.0         2       1.00          710
21584   952006823 2014-12-02   380000.0         3       2.50         1260
21585  3832050760 2014-08-28   270000.0         3       2.50         1870
21586  2767604724 2014-10-15   505000.0         2       2.50         1430
21587  6632300207 2015-03-05   385000.0         3       2.50         1520
21588  2767600688 2014-11-13   414500.0         2       1.50         1210
21589  7570050450 2014-09-10   347500.0         3       2.50         2540
21590  7430200100 2014-05-14  1222500.0         4       3.50         4910
21591  4140940150 2014-10-02   572000.0         4       2.75         2770
21592  1931300412 2015-04-16   475000.0         3       2.25         1190
21593  8672200110 2015-03-17  1088000.0         5       3.75         4170
21594  5087900040 2014-10-17   350000.0         4       2.75         2500
21595  1972201967 2014-10-31   520000.0         2       2.25         1530
21596  7502800100 2014-08-13   679950.0         5       2.75         3600
21597   191100405 2015-04-21  1575000.0         4       3.25         3410
21598  8956200760 2014-10-13   541800.0         4       2.50         3118
21599  7202300110 2014-09-15   810000.0         4       3.00         3990
21600   249000205 2014-10-15  1537000.0         5       3.75         4470
21601  5100403806 2015-04-07   467000.0         3       2.50         1425
21602   844000965 2014-06-26   224000.0         3       1.75         1500
21603  7852140040 2014-08-25   507250.0         3       2.50         2270
21604  9834201367 2015-01-26   429000.0         3       2.00         1490
21605  3448900210 2014-10-14   610685.0         4       2.50         2520
21606  7936000429 2015-03-26  1007500.0         4       3.50         3510
21607  2997800021 2015-02-19   475000.0         3       2.50         1310
21608   263000018 2014-05-21   360000.0         3       2.50         1530
21609  6600060120 2015-02-23   400000.0         4       2.50         2310
21610  1523300141 2014-06-23   402101.0         2       0.75         1020
21611   291310100 2015-01-16   400000.0         3       2.50         1600
21612  1523300157 2014-10-15   325000.0         2       0.75         1020

       sqft_lot  floors  waterfront  view  ...  sqft_basement  houseagenow  \
0          5650     1.0           0     0  ...              0         1955
1          7242     2.0           0     0  ...            400         1951
2         10000     1.0           0     0  ...              0         1933
3          5000     1.0           0     0  ...            910         1965
4          8080     1.0           0     0  ...              0         1987
5        101930     1.0           0     0  ...           1530         2001
6          6819     2.0           0     0  ...              0         1995
7          9711     1.0           0     0  ...              0         1963
8          7470     1.0           0     0  ...            730         1960
9          6560     2.0           0     0  ...              0         2003
10         9796     1.0           0     0  ...           1700         1965
11         6000     1.0           0     0  ...            300         1942
12        19901     1.5           0     0  ...              0         1927
13         9680     1.0           0     0  ...              0         1977
14         4850     1.5           0     0  ...              0         1900
15         5000     2.0           0     3  ...            970         1979
16        14040     2.0           0     0  ...              0         1994
17         4300     1.5           0     0  ...              0         1916
18         9850     1.0           0     0  ...              0         1921
19         9774     1.0           0     0  ...              0         1969
20         4980     1.0           0     0  ...            760         1947
21        44867     1.0           0     4  ...            720         1968
22         6300     2.0           0     0  ...              0         1995
23         9643     1.0           0     0  ...              0         1985
24         6500     2.0           0     0  ...              0         1985
25         4697     1.5           0     0  ...              0         1941
26         2691     2.0           0     0  ...            700         1915
27         1581     1.5           0     0  ...              0         1909
28         6380     1.0           0     0  ...            730         1948
29         7173     2.0           0     0  ...              0         2005
...         ...     ...         ...   ...  ...            ...          ...
21583      1157     2.0           0     0  ...              0         1943
21584       900     2.0           0     0  ...            320         2007
21585      5000     2.0           0     0  ...              0         2009
21586      1201     3.0           0     0  ...              0         2009
21587      1488     3.0           0     0  ...              0         2006
21588      1278     2.0           0     0  ...            190         2007
21589      4760     2.0           0     0  ...              0         2010
21590      9444     1.5           0     0  ...           1800         2007
21591      3852     2.0           0     0  ...              0         2014
21592      1200     3.0           0     0  ...              0         2008
21593      8142     2.0           0     2  ...              0         2006
21594      5995     2.0           0     0  ...              0         2008
21595       981     3.0           0     0  ...             50         2006
21596      9437     2.0           0     0  ...              0         2014
21597     10125     2.0           0     0  ...              0         2007
21598      7866     2.0           0     2  ...              0         2014
21599      7838     2.0           0     0  ...              0         2003
21600      8088     2.0           0     0  ...              0         2008
21601      1179     3.0           0     0  ...              0         2008
21602     11968     1.0           0     0  ...              0         2014
21603      5536     2.0           0     0  ...              0         2003
21604      1126     3.0           0     0  ...              0         2014
21605      6023     2.0           0     0  ...              0         2014
21606      7200     2.0           0     0  ...            910         2009
21607      1294     2.0           0     0  ...            130         2008
21608      1131     3.0           0     0  ...              0         2009
21609      5813     2.0           0     0  ...              0         2014
21610      1350     2.0           0     0  ...              0         2009
21611      2388     2.0           0     0  ...              0         2004
21612      1076     2.0           0     0  ...              0         2008

       yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  \
0                 0    98178  47.5112 -122.257           1340        5650
1              1991    98125  47.7210 -122.319           1690        7639
2                 0    98028  47.7379 -122.233           2720        8062
3                 0    98136  47.5208 -122.393           1360        5000
4                 0    98074  47.6168 -122.045           1800        7503
5                 0    98053  47.6561 -122.005           4760      101930
6                 0    98003  47.3097 -122.327           2238        6819
7                 0    98198  47.4095 -122.315           1650        9711
8                 0    98146  47.5123 -122.337           1780        8113
9                 0    98038  47.3684 -122.031           2390        7570
10                0    98007  47.6007 -122.145           2210        8925
11                0    98115  47.6900 -122.292           1330        6000
12                0    98028  47.7558 -122.229           1780       12697
13                0    98074  47.6127 -122.045           1370       10208
14                0    98107  47.6700 -122.394           1360        4850
15                0    98126  47.5714 -122.375           2140        4000
16                0    98019  47.7277 -121.962           1890       14018
17                0    98103  47.6648 -122.343           1610        4300
18                0    98002  47.3089 -122.210           1060        5095
19                0    98003  47.3343 -122.306           1280        8850
20                0    98133  47.7025 -122.341           1400        4980
21                0    98040  47.5316 -122.233           4110       20336
22                0    98092  47.3266 -122.169           2240        7005
23                0    98030  47.3533 -122.166           1220        8386
24                0    98030  47.3739 -122.172           2200        6865
25                0    98002  47.3048 -122.218           1030        4705
26                0    98119  47.6386 -122.360           1760        3573
27                0    98112  47.6221 -122.314           1860        3861
28                0    98115  47.6950 -122.304           1520        6235
29                0    98052  47.7073 -122.110           2630        6026
...             ...      ...      ...      ...            ...         ...
21583             0    98102  47.6413 -122.329           1370        1173
21584             0    98116  47.5621 -122.384           1310        1415
21585             0    98042  47.3339 -122.055           2170        5399
21586             0    98107  47.6707 -122.381           1430        1249
21587             0    98125  47.7337 -122.309           1520        1497
21588             0    98117  47.6756 -122.375           1210        1118
21589             0    98038  47.3452 -122.022           2540        4571
21590             0    98074  47.6502 -122.066           4560       11063
21591             0    98178  47.5001 -122.232           1810        5641
21592             0    98103  47.6542 -122.346           1180        1224
21593             0    98056  47.5354 -122.181           3030        7980
21594             0    98042  47.3749 -122.107           2530        5988
21595             0    98103  47.6533 -122.346           1530        1282
21596             0    98059  47.4822 -122.131           3550        9421
21597             0    98040  47.5653 -122.223           2290       10125
21598             0    98001  47.2931 -122.264           2673        6500
21599             0    98053  47.6857 -122.046           3370        6814
21600             0    98004  47.6321 -122.200           2780        8964
21601             0    98125  47.6963 -122.318           1285        1253
21602             0    98010  47.3095 -122.002           1320       11303
21603             0    98065  47.5389 -121.881           2270        5731
21604             0    98144  47.5699 -122.288           1400        1230
21605             0    98056  47.5137 -122.167           2520        6023
21606             0    98136  47.5537 -122.398           2050        6200
21607             0    98116  47.5773 -122.409           1330        1265
21608             0    98103  47.6993 -122.346           1530        1509
21609             0    98146  47.5107 -122.362           1830        7200
21610             0    98144  47.5944 -122.299           1020        2007
21611             0    98027  47.5345 -122.069           1410        1287
21612             0    98144  47.5941 -122.299           1020        1357

       month  year
0         10  2014
1         12  2014
2          2  2015
3         12  2014
4          2  2015
5          5  2014
6          6  2014
7          1  2015
8          4  2015
9          3  2015
10         4  2015
11         5  2014
12         5  2014
13        10  2014
14         3  2015
15         1  2015
16         7  2014
17         5  2014
18        12  2014
19         4  2015
20         5  2014
21         8  2014
22         7  2014
23         5  2014
24        11  2014
25        11  2014
26         6  2014
27        12  2014
28         6  2014
29         3  2015
...      ...   ...
21583      6  2014
21584     12  2014
21585      8  2014
21586     10  2014
21587      3  2015
21588     11  2014
21589      9  2014
21590      5  2014
21591     10  2014
21592      4  2015
21593      3  2015
21594     10  2014
21595     10  2014
21596      8  2014
21597      4  2015
21598     10  2014
21599      9  2014
21600     10  2014
21601      4  2015
21602      6  2014
21603      8  2014
21604      1  2015
21605     10  2014
21606      3  2015
21607      2  2015
21608      5  2014
21609      2  2015
21610      6  2014
21611      1  2015
21612     10  2014

[21613 rows x 23 columns]

In [14]:
data.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'houseagenow', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15', 'month', 'year'],
      dtype='object')

In [15]:
data['year_since_renovation']=curryear -data['yr_renovated']
print(data['year_since_renovation'])

0        2019
1          28
2        2019
3        2019
4        2019
5        2019
6        2019
7        2019
8        2019
9        2019
10       2019
11       2019
12       2019
13       2019
14       2019
15       2019
16       2019
17       2019
18       2019
19       2019
20       2019
21       2019
22       2019
23       2019
24       2019
25       2019
26       2019
27       2019
28       2019
29       2019
         ...
21583    2019
21584    2019
21585    2019
21586    2019
21587    2019
21588    2019
21589    2019
21590    2019
21591    2019
21592    2019
21593    2019
21594    2019
21595    2019
21596    2019
21597    2019
21598    2019
21599    2019
21600    2019
21601    2019
21602    2019
21603    2019
21604    2019
21605    2019
21606    2019
21607    2019
21608    2019
21609    2019
21610    2019
21611    2019
21612    2019
Name: year_since_renovation, Length: 21613, dtype: int64

In [16]:
y=data['price']

print(y)

0         221900.0
1         538000.0
2         180000.0
3         604000.0
4         510000.0
5        1225000.0
6         257500.0
7         291850.0
8         229500.0
9         323000.0
10        662500.0
11        468000.0
12        310000.0
13        400000.0
14        530000.0
15        650000.0
16        395000.0
17        485000.0
18        189000.0
19        230000.0
20        385000.0
21       2000000.0
22        285000.0
23        252700.0
24        329000.0
25        233000.0
26        937000.0
27        667000.0
28        438000.0
29        719000.0
           ...
21583     399950.0
21584     380000.0
21585     270000.0
21586     505000.0
21587     385000.0
21588     414500.0
21589     347500.0
21590    1222500.0
21591     572000.0
21592     475000.0
21593    1088000.0
21594     350000.0
21595     520000.0
21596     679950.0
21597    1575000.0
21598     541800.0
21599     810000.0
21600    1537000.0
21601     467000.0
21602     224000.0
21603     507250.0
21604     429000.0
21605     610685.0
21606    1007500.0
21607     475000.0
21608     360000.0
21609     400000.0
21610     402101.0
21611     400000.0
21612     325000.0
Name: price, Length: 21613, dtype: float64

In [17]:
corr=data.corr()    #library function for co-relation. -ve means 0 corelation 
corr

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,houseagenow,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,month,year,year_since_renovation
id,1.000000,-0.016762,0.001286,0.005160,-0.012258,-0.132109,0.018525,-0.002721,0.011592,-0.023783,...,0.021380,-0.016907,-0.008224,-0.001891,0.020799,-0.002901,-0.138798,-0.011708,0.010128,0.016907
price,-0.016762,1.000000,0.308350,0.525138,0.702035,0.089661,0.256794,0.266369,0.397293,0.036362,...,0.054012,0.126434,-0.053203,0.307003,0.021626,0.585379,0.082447,-0.010081,0.003576,-0.126434
bedrooms,0.001286,0.308350,1.000000,0.515884,0.576671,0.031703,0.175429,-0.006582,0.079532,0.028472,...,0.154178,0.018841,-0.152668,-0.008931,0.129473,0.391638,0.029244,-0.001533,-0.009838,-0.018841
bathrooms,0.005160,0.525138,0.515884,1.000000,0.754665,0.087740,0.500653,0.063744,0.187737,-0.124982,...,0.506019,0.050739,-0.203866,0.024573,0.223042,0.568634,0.087175,0.007392,-0.026596,-0.050739
sqft_living,-0.012258,0.702035,0.576671,0.754665,1.000000,0.172826,0.353949,0.103818,0.284611,-0.058753,...,0.318049,0.055363,-0.199430,0.052529,0.240223,0.756420,0.183286,0.011810,-0.029038,-0.055363
sqft_lot,-0.132109,0.089661,0.031703,0.087740,0.172826,1.000000,-0.005201,0.021604,0.074710,-0.008958,...,0.053080,0.007644,-0.129574,-0.085683,0.229521,0.144608,0.718557,-0.002369,0.005468,-0.007644
floors,0.018525,0.256794,0.175429,0.500653,0.353949,-0.005201,1.000000,0.023698,0.029444,-0.263768,...,0.489319,0.006338,-0.059121,0.049614,0.125419,0.279885,-0.011269,0.014005,-0.022315,-0.006338
waterfront,-0.002721,0.266369,-0.006582,0.063744,0.103818,0.021604,0.023698,1.000000,0.401857,0.016653,...,-0.026161,0.092885,0.030285,-0.014274,-0.041910,0.086463,0.030703,0.008132,-0.004165,-0.092885
view,0.011592,0.397293,0.079532,0.187737,0.284611,0.074710,0.029444,0.401857,1.000000,0.045990,...,-0.053440,0.103917,0.084827,0.006157,-0.078400,0.280439,0.072575,-0.005638,0.001364,-0.103917
condition,-0.023783,0.036362,0.028472,-0.124982,-0.058753,-0.008958,-0.263768,0.016653,0.045990,1.000000,...,-0.361417,-0.060618,0.003026,-0.014941,-0.106500,-0.092824,-0.003406,0.021978,-0.045589,0.060618
grade,0.008130,0.667434,0.356967,0.664983,0.762704,0.113621,0.458183,0.082775,0.251321,-0.144674,...,0.446963,0.014414,-0.184862,0.114084,0.198372,0.713202,0.119248,0.008376,-0.030387,-0.014414
sqft_above,-0.010842,0.605567,0.477600,0.685342,0.876597,0.183512,0.523885,0.072075,0.167649,-0.158214,...,0.423898,0.023285,-0.261190,-0.000816,0.343803,0.731870,0.194050,0.009872,-0.023823,-0.023285
sqft_basement,-0.005151,0.323816,0.303093,0.283770,0.435043,0.015286,-0.245705,0.080588,0.276947,0.174105,...,-0.133124,0.071323,0.074845,0.110538,-0.144765,0.200355,0.017276,0.006035,-0.015687,-0.071323
houseagenow,0.021380,0.054012,0.154178,0.506019,0.318049,0.053080,0.489319,-0.026161,-0.053440,-0.361417,...,1.000000,-0.224874,-0.346869,-0.148122,0.409356,0.326229,0.070958,-0.006226,0.003507,0.224874
yr_renovated,-0.016907,0.126434,0.018841,0.050739,0.055363,0.007644,0.006338,0.092885,0.103917,-0.060618,...,-0.224874,1.000000,0.064357,0.029398,-0.068372,-0.002673,0.007854,0.012827,-0.023707,-1.000000
zipcode,-0.008224,-0.053203,-0.152668,-0.203866,-0.199430,-0.129574,-0.059121,0.030285,0.084827,0.003026,...,-0.346869,0.064357,1.000000,0.267048,-0.564072,-0.279033,-0.147221,-0.000171,0.001189,-0.064357
lat,-0.001891,0.307003,-0.008931,0.024573,0.052529,-0.085683,0.049614,-0.014274,0.006157,-0.014941,...,-0.148122,0.029398,0.267048,1.000000,-0.135512,0.048858,-0.086419,0.014961,-0.029212,-0.029398
long,0.020799,0.021626,0.129473,0.223042,0.240223,0.229521,0.125419,-0.041910,-0.078400,-0.106500,...,0.409356,-0.068372,-0.564072,-0.135512,1.000000,0.334605,0.254451,-0.008134,0.000270,0.068372
sqft_living15,-0.002901,0.585379,0.391638,0.568634,0.756420,0.144608,0.279885,0.086463,0.280439,-0.092824,...,0.326229,-0.002673,-0.279033,0.048858,0.334605,1.000000,0.183192,0.002449,-0.021734,0.002673
sqft_lot15,-0.138798,0.082447,0.029244,0.087175,0.183286,0.718557,-0.011269,0.030703,0.072575,-0.003406,...,0.070958,0.007854,-0.147221,-0.086419,0.254451,0.183192,1.000000,0.003546,-0.000085,-0.007854
month,-0.011708,-0.010081,-0.001533,0.007392,0.011810,-0.002369,0.014005,0.008132,-0.005638,0.021978,...,-0.006226,0.012827,-0.000171,0.014961,-0.008134,0.002449,0.003546,1.000000,-0.782389,-0.012827
year,0.010128,0.003576,-0.009838,-0.026596,-0.029038,0.005468,-0.022315,-0.004165,0.001364,-0.045589,...,0.003507,-0.023707,0.001189,-0.029212,0.000270,-0.021734,-0.000085,-0.782389,1.000000,0.023707
year_since_renovation,0.016907,-0.126434,-0.018841,-0.050739,-0.055363,-0.007644,-0.006338,-0.092885,-0.103917,0.060618,...,0.224874,-1.000000,-0.064357,-0.029398,0.068372,0.002673,-0.007854,-0.012827,0.023707,1.000000

In [18]:
corr.nlargest(21,'price')['price']     #21st highest corelation columns to price (higher it is better it is)

price            1.000000
sqft_living      0.702035
grade            0.667434
sqft_above       0.605567
sqft_living15    0.585379
bathrooms        0.525138
view             0.397293
sqft_basement    0.323816
bedrooms         0.308350
lat              0.307003
waterfront       0.266369
floors           0.256794
yr_renovated     0.126434
sqft_lot         0.089661
sqft_lot15       0.082447
houseagenow      0.054012
condition        0.036362
long             0.021626
year             0.003576
month           -0.010081
id              -0.016762
Name: price, dtype: float64

In [19]:
x=data[['bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view','condition','grade','sqft_above','sqft_basement','houseagenow','yr_renovated','zipcode','sqft_living15','sqft_lot15','month','year','year_since_renovation']]

In [20]:
data.drop('price',axis=1)     #drops column. axis 1 => rows

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,houseagenow,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,month,year,year_since_renovation
0,7129300520,2014-10-13,3,1.00,1180,5650,1.0,0,0,3,...,1955,0,98178,47.5112,-122.257,1340,5650,10,2014,2019
1,6414100192,2014-12-09,3,2.25,2570,7242,2.0,0,0,3,...,1951,1991,98125,47.7210,-122.319,1690,7639,12,2014,28
2,5631500400,2015-02-25,2,1.00,770,10000,1.0,0,0,3,...,1933,0,98028,47.7379,-122.233,2720,8062,2,2015,2019
3,2487200875,2014-12-09,4,3.00,1960,5000,1.0,0,0,5,...,1965,0,98136,47.5208,-122.393,1360,5000,12,2014,2019
4,1954400510,2015-02-18,3,2.00,1680,8080,1.0,0,0,3,...,1987,0,98074,47.6168,-122.045,1800,7503,2,2015,2019
5,7237550310,2014-05-12,4,4.50,5420,101930,1.0,0,0,3,...,2001,0,98053,47.6561,-122.005,4760,101930,5,2014,2019
6,1321400060,2014-06-27,3,2.25,1715,6819,2.0,0,0,3,...,1995,0,98003,47.3097,-122.327,2238,6819,6,2014,2019
7,2008000270,2015-01-15,3,1.50,1060,9711,1.0,0,0,3,...,1963,0,98198,47.4095,-122.315,1650,9711,1,2015,2019
8,2414600126,2015-04-15,3,1.00,1780,7470,1.0,0,0,3,...,1960,0,98146,47.5123,-122.337,1780,8113,4,2015,2019
9,3793500160,2015-03-12,3,2.50,1890,6560,2.0,0,0,3,...,2003,0,98038,47.3684,-122.031,2390,7570,3,2015,2019
10,1736800520,2015-04-03,3,2.50,3560,9796,1.0,0,0,3,...,1965,0,98007,47.6007,-122.145,2210,8925,4,2015,2019
11,9212900260,2014-05-27,2,1.00,1160,6000,1.0,0,0,4,...,1942,0,98115,47.6900,-122.292,1330,6000,5,2014,2019
12,114101516,2014-05-28,3,1.00,1430,19901,1.5,0,0,4,...,1927,0,98028,47.7558,-122.229,1780,12697,5,2014,2019
13,6054650070,2014-10-07,3,1.75,1370,9680,1.0,0,0,4,...,1977,0,98074,47.6127,-122.045,1370,10208,10,2014,2019
14,1175000570,2015-03-12,5,2.00,1810,4850,1.5,0,0,3,...,1900,0,98107,47.6700,-122.394,1360,4850,3,2015,2019
15,9297300055,2015-01-24,4,3.00,2950,5000,2.0,0,3,3,...,1979,0,98126,47.5714,-122.375,2140,4000,1,2015,2019
16,1875500060,2014-07-31,3,2.00,1890,14040,2.0,0,0,3,...,1994,0,98019,47.7277,-121.962,1890,14018,7,2014,2019
17,6865200140,2014-05-29,4,1.00,1600,4300,1.5,0,0,4,...,1916,0,98103,47.6648,-122.343,1610,4300,5,2014,2019
18,16000397,2014-12-05,2,1.00,1200,9850,1.0,0,0,4,...,1921,0,98002,47.3089,-122.210,1060,5095,12,2014,2019
19,7983200060,2015-04-24,3,1.00,1250,9774,1.0,0,0,4,...,1969,0,98003,47.3343,-122.306,1280,8850,4,2015,2019
20,6300500875,2014-05-14,4,1.75,1620,4980,1.0,0,0,4,...,1947,0,98133,47.7025,-122.341,1400,4980,5,2014,2019
21,2524049179,2014-08-26,3,2.75,3050,44867,1.0,0,4,3,...,1968,0,98040,47.5316,-122.233,4110,20336,8,2014,2019
22,7137970340,2014-07-03,5,2.50,2270,6300,2.0,0,0,3,...,1995,0,98092,47.3266,-122.169,2240,7005,7,2014,2019
23,8091400200,2014-05-16,2,1.50,1070,9643,1.0,0,0,3,...,1985,0,98030,47.3533,-122.166,1220,8386,5,2014,2019
24,3814700200,2014-11-20,3,2.25,2450,6500,2.0,0,0,4,...,1985,0,98030,47.3739,-122.172,2200,6865,11,2014,2019
25,1202000200,2014-11-03,3,2.00,1710,4697,1.5,0,0,5,...,1941,0,98002,47.3048,-122.218,1030,4705,11,2014,2019
26,1794500383,2014-06-26,3,1.75,2450,2691,2.0,0,0,3,...,1915,0,98119,47.6386,-122.360,1760,3573,6,2014,2019
27,3303700376,2014-12-01,3,1.00,1400,1581,1.5,0,0,5,...,1909,0,98112,47.6221,-122.314,1860,3861,12,2014,2019
28,5101402488,2014-06-24,3,1.75,1520,6380,1.0,0,0,3,...,1948,0,98115,47.6950,-122.304,1520,6235,6,2014,2019
29,1873100390,2015-03-02,4,2.50,2570,7173,2.0,0,0,3,...,2005,0,98052,47.7073,-122.110,2630,6026,3,2015,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21583,2025049203,2014-06-10,2,1.00,710,1157,2.0,0,0,4,...,1943,0,98102,47.6413,-122.329,1370,1173,6,2014,2019
21584,952006823,2014-12-02,3,2.50,1260,900,2.0,0,0,3,...,2007,0,98116,47.5621,-122.384,1310,1415,12,2014,2019
21585,3832050760,2014-08-28,3,2.50,1870,5000,2.0,0,0,3,...,2009,0,98042,47.3339,-122.055,2170,5399,8,2014,2019
21586,2767604724,2014-10-15,2,2.50,1430,1201,3.0,0,0,3,...,2009,0,98107,47.6707,-122.381,1430,1249,10,2014,2019
21587,6632300207,2015-03-05,3,2.50,1520,1488,3.0,0,0,3,...,2006,0,98125,47.7337,-122.309,1520,1497,3,2015,2019
21588,2767600688,2014-11-13,2,1.50,1210,1278,2.0,0,0,3,...,2007,0,98117,47.6756,-122.375,1210,1118,11,2014,2019
21589,7570050450,2014-09-10,3,2.50,2540,4760,2.0,0,0,3,...,2010,0,98038,47.3452,-122.022,2540,4571,9,2014,2019
21590,7430200100,2014-05-14,4,3.50,4910,9444,1.5,0,0,3,...,2007,0,98074,47.6502,-122.066,4560,11063,5,2014,2019
21591,4140940150,2014-10-02,4,2.75,2770,3852,2.0,0,0,3,...,2014,0,98178,47.5001,-122.232,1810,5641,10,2014,2019
21592,1931300412,2015-04-16,3,2.25,1190,1200,3.0,0,0,3,...,2008,0,98103,47.6542,-122.346,1180,1224,4,2015,2019
21593,8672200110,2015-03-17,5,3.75,4170,8142,2.0,0,2,3,...,2006,0,98056,47.5354,-122.181,3030,7980,3,2015,2019
21594,5087900040,2014-10-17,4,2.75,2500,5995,2.0,0,0,3,...,2008,0,98042,47.3749,-122.107,2530,5988,10,2014,2019
21595,1972201967,2014-10-31,2,2.25,1530,981,3.0,0,0,3,...,2006,0,98103,47.6533,-122.346,1530,1282,10,2014,2019
21596,7502800100,2014-08-13,5,2.75,3600,9437,2.0,0,0,3,...,2014,0,98059,47.4822,-122.131,3550,9421,8,2014,2019
21597,191100405,2015-04-21,4,3.25,3410,10125,2.0,0,0,3,...,2007,0,98040,47.5653,-122.223,2290,10125,4,2015,2019
21598,8956200760,2014-10-13,4,2.50,3118,7866,2.0,0,2,3,...,2014,0,98001,47.2931,-122.264,2673,6500,10,2014,2019
21599,7202300110,2014-09-15,4,3.00,3990,7838,2.0,0,0,3,...,2003,0,98053,47.6857,-122.046,3370,6814,9,2014,2019
21600,249000205,2014-10-15,5,3.75,4470,8088,2.0,0,0,3,...,2008,0,98004,47.6321,-122.200,2780,8964,10,2014,2019
21601,5100403806,2015-04-07,3,2.50,1425,1179,3.0,0,0,3,...,2008,0,98125,47.6963,-122.318,1285,1253,4,2015,2019
21602,844000965,2014-06-26,3,1.75,1500,11968,1.0,0,0,3,...,2014,0,98010,47.3095,-122.002,1320,11303,6,2014,2019
21603,7852140040,2014-08-25,3,2.50,2270,5536,2.0,0,0,3,...,2003,0,98065,47.5389,-121.881,2270,5731,8,2014,2019
21604,9834201367,2015-01-26,3,2.00,1490,1126,3.0,0,0,3,...,2014,0,98144,47.5699,-122.288,1400,1230,1,2015,2019
21605,3448900210,2014-10-14,4,2.50,2520,6023,2.0,0,0,3,...,2014,0,98056,47.5137,-122.167,2520,6023,10,2014,2019
21606,7936000429,2015-03-26,4,3.50,3510,7200,2.0,0,0,3,...,2009,0,98136,47.5537,-122.398,2050,6200,3,2015,2019
21607,2997800021,2015-02-19,3,2.50,1310,1294,2.0,0,0,3,...,2008,0,98116,47.5773,-122.409,1330,1265,2,2015,2019
21608,263000018,2014-05-21,3,2.50,1530,1131,3.0,0,0,3,...,2009,0,98103,47.6993,-122.346,1530,1509,5,2014,2019
21609,6600060120,2015-02-23,4,2.50,2310,5813,2.0,0,0,3,...,2014,0,98146,47.5107,-122.362,1830,7200,2,2015,2019
21610,1523300141,2014-06-23,2,0.75,1020,1350,2.0,0,0,3,...,2009,0,98144,47.5944,-122.299,1020,2007,6,2014,2019
21611,291310100,2015-01-16,3,2.50,1600,2388,2.0,0,0,3,...,2004,0,98027,47.5345,-122.069,1410,1287,1,2015,2019
21612,1523300157,2014-10-15,2,0.75,1020,1076,2.0,0,0,3,...,2008,0,98144,47.5941,-122.299,1020,1357,10,2014,2019

In [21]:
corr.nlargest(21,'price')['price']

price            1.000000
sqft_living      0.702035
grade            0.667434
sqft_above       0.605567
sqft_living15    0.585379
bathrooms        0.525138
view             0.397293
sqft_basement    0.323816
bedrooms         0.308350
lat              0.307003
waterfront       0.266369
floors           0.256794
yr_renovated     0.126434
sqft_lot         0.089661
sqft_lot15       0.082447
houseagenow      0.054012
condition        0.036362
long             0.021626
year             0.003576
month           -0.010081
id              -0.016762
Name: price, dtype: float64

In [22]:
#TRY - 1

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=0)  #train testing. 0.8=> 80% training set

In [23]:
reg=LinearRegression()                  #linear regression is implied on training set
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
reg.score(x_test,y_test)       #checks accuracy

0.6462159617576948

In [25]:
accuracy=reg.score(x_test,y_test)     
accuracy

0.6462159617576948

In [26]:
#TRY - 2

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=0)  #train testing. 0.8=> 80% training set

In [27]:
reg=LinearRegression()                  #linear regression is implied on training set
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
reg.score(x_test,y_test)       #checks accuracy

0.6444756173633455

In [29]:
mlist=[mlist/10000 for mlist in range (1,9999)] #creates a list of x from 0.01 to 0.99

In [30]:
max=0
curr=0

In [31]:
#Sort for max accuracy

x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.0001,random_state=0)
reg=LinearRegression()                  #linear regression is implied on training set
reg.fit(x_train,y_train)
reg.score(x_test,y_test)                #checks accuracy 

curr=reg.score(x_test,y_test) 

for i in mlist:
    x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=i,random_state=0)
    
    reg=LinearRegression()              #linear regression is implied on training set
    reg.fit(x_train,y_train)
    
    reg.score(x_test,y_test) 
    
    accuracy=reg.score(x_test,y_test)  
    
    if(accuracy>=curr):
        max=i
        curr=accuracy
        
max=max*100
curr=curr*100
print(f"The maximum accuracy of {curr:1.4}% is at {max}% of train data")

The maximum accuracy of 97.25% is at 99.98% of train data